config/routes.rb
Skilllist::Application.routes.draw do
  resources :skilllevels

  resources :technologies

  resources :employees

  root :to => "skilllevels#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :skilllevels
  has_many :technologies, :through => :skilllevels
 
end

app/models/skilllevel.rb
class Skilllevel < ActiveRecord::Base
  belongs_to :employee
  belongs_to :technology
  
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  has_many :skilllevels
  has_many :employees, :through => :skilllevels

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.xml
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.xml
  def show
    @employee = Employee.find(params[:id])
    @technos = Technology.find(:all)
    @skills = @employee.skilllevels

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.xml
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.xml
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to(@employee, :notice => 'Employee was successfully created.') }
        format.xml  { render :xml => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.xml
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to(@employee, :notice => 'Employee was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.xml
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to(employees_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/skilllevels_controller.rb
class SkilllevelsController < ApplicationController
  # GET /skilllevels
  # GET /skilllevels.xml

  def index
    @employee = Employee.find(:first)
    redirect_to skilllevel_path(@employee)
  end

  def show
    @employees = Employee.find(:all)
    @employee = Employee.find(params[:id])
    @technos = Technology.find(:all)
    @skills = @employee.skilllevels

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  def update
    @employee = Employee.find(params[:employee_id])
    logger.debug @employee.inspect
    respond_to do |format|
      if @employee
        @employee.skilllevels.destroy_all
        logger.debug params[:skilllevels]
        params[:skilllevels].each do |id, skills|
          logger.debug id
          logger.debug skills
          if not skills[:title].blank? and not skills[:years_exp].blank?
            Skilllevel.create(:employee_id => @employee.id, :technology_id => id, :title => skills[:title], :years_exp => skills[:years_exp])
          end
        end
        format.html { redirect_to(skilllevel_path(@employee), :notice => 'Employee was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  # GET /technologies
  # GET /technologies.xml
  def index
    @technologies = Technology.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @technologies }
    end
  end

  # GET /technologies/1
  # GET /technologies/1.xml
  def show
    @technology = Technology.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @technology }
    end
  end

  # GET /technologies/new
  # GET /technologies/new.xml
  def new
    @technology = Technology.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @technology }
    end
  end

  # GET /technologies/1/edit
  def edit
    @technology = Technology.find(params[:id])
  end

  # POST /technologies
  # POST /technologies.xml
  def create
    @technology = Technology.new(params[:technology])

    respond_to do |format|
      if @technology.save
        format.html { redirect_to(@technology, :notice => 'Technology was successfully created.') }
        format.xml  { render :xml => @technology, :status => :created, :location => @technology }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @technology.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /technologies/1
  # PUT /technologies/1.xml
  def update
    @technology = Technology.find(params[:id])

    respond_to do |format|
      if @technology.update_attributes(params[:technology])
        format.html { redirect_to(@technology, :notice => 'Technology was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @technology.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.xml
  def destroy
    @technology = Technology.find(params[:id])
    @technology.destroy

    respond_to do |format|
      format.html { redirect_to(technologies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/skilllevels_helper.rb
module SkilllevelsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>
<br>
<br>
<%= link_to 'Technologies', technologies_path %> | <%= link_to 'Connaissances', skilllevels_path %> 

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skilllist</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/skilllevels/_form.html.erb
<%= form_for(@skilllevel) do |f| %>
  <% if @skilllevel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skilllevel.errors.count, "error") %> prohibited this skilllevel from being saved:</h2>

      <ul>
      <% @skilllevel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :years_exp %><br />
    <%= f.text_field :years_exp %>
  </div>
  <div class="field">
    <%= f.label :technology_id %><br />
    <%= f.text_field :technology_id %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.text_field :employee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skilllevels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% form_tag skilllevel_path, :method => :put do %>
      <b>Name:</b>
      <%= select_tag :employee_id, options_from_collection_for_select(@employees, :id, :name, @employee.id), :onchange => "document.location.href='#{skilllevels_url}/' + this.value;" %>
      <br><br>
      <table border="1">
        <tr>
          <td>Technologie</td>
          <td>Titre</td>
          <td>Annees d'experience</td>
        </tr>
        <% @technos.each do |tech| %>
            <tr>
              <% skill = @skills.detect {|s| s.technology_id == tech.id} %>
              <td><%= tech.name %></td>
              <td><%= select_tag "skilllevels[#{tech.id}][title]", options_for_select([["-- Selectionner --",""], "Expert", "Intermediere", "Novice"], skill ? skill.title : "") %></td>
              <td><%= text_field_tag "skilllevels[#{tech.id}][years_exp]", skill ? skill.years_exp : "", {:maxlength => 2, :size => 3} %></td>
            </tr>
        <% end %>
      </table>

      <%= submit_tag "Sauvegarder" %>
  <% end %>

  </p>
  <br>
  <br>

  <%= link_to 'Employee', employees_path %> |
  <%= link_to 'Technologies', technologies_path %>

app/views/technologies/_form.html.erb
<%= form_for(@technology) do |f| %>
  <% if @technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% @technology.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<h1>Editing technology</h1>

<%= render 'form' %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<h1>Listing technologies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @technologies.each do |technology| %>
  <tr>
    <td><%= technology.name %></td>
    <td><%= link_to 'Show', technology %></td>
    <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
    <td><%= link_to 'Destroy', technology, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouvelle Technologie', new_technology_path %>
<br>
<br>
<%= link_to 'Employee', employees_path %> | <%= link_to 'Connaissances', skilllevels_path %>

app/views/technologies/new.html.erb
<h1>New technology</h1>

<%= render 'form' %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @technology.name %>
</p>


<%= link_to 'Edit', edit_technology_path(@technology) %> |
<%= link_to 'Back', technologies_path %>